-- ================================================================
-- Base Schema: Council App
-- ================================================================
-- Run this FIRST in Supabase Dashboard → SQL Editor
-- ================================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ────────────────────────────────────────────────────────────────
-- PROFILES
-- One row per user, auto-created on signup via trigger
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
  id                  UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email               TEXT,
  full_name           TEXT,
  avatar_url          TEXT,
  domain              TEXT,
  bio                 TEXT,
  plan                TEXT NOT NULL DEFAULT 'free',    -- 'free' | 'pro' | 'team'
  credits_remaining   INTEGER NOT NULL DEFAULT 5,
  credits_reset_at    TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '1 month'),
  -- Cashfree billing fields
  cashfree_order_id       TEXT,
  subscription_plan       TEXT,
  subscription_active     BOOLEAN DEFAULT FALSE,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Credits can never go negative
ALTER TABLE profiles
  DROP CONSTRAINT IF EXISTS credits_non_negative;
ALTER TABLE profiles
  ADD CONSTRAINT credits_non_negative CHECK (credits_remaining >= 0);

-- ────────────────────────────────────────────────────────────────
-- TEMPLATES
-- Custom advisor panels users can save and reuse
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS templates (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id          UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  name             TEXT NOT NULL,
  slug             TEXT UNIQUE,
  advisor_panel    JSONB DEFAULT '[]',
  chairman_prompt  TEXT,
  is_public        BOOLEAN DEFAULT FALSE,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────────
-- COUNCILS
-- Each council run — question, advisor responses, verdict
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS councils (
  id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id           UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  template_id       UUID REFERENCES templates(id) ON DELETE SET NULL,
  question          TEXT NOT NULL,
  title             TEXT,                          -- short slug generated by pipeline
  context           JSONB DEFAULT '{}',            -- optional background context
  status            TEXT DEFAULT 'running',        -- running | advisors | review | chairman | complete | failed
  advisor_responses JSONB DEFAULT '[]',
  letter_map        JSONB DEFAULT '{}',
  reviews           JSONB DEFAULT '[]',
  verdict           TEXT,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  completed_at      TIMESTAMPTZ
);

-- ────────────────────────────────────────────────────────────────
-- TRIGGER: auto-create profile on signup
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO profiles (id, email, full_name, avatar_url)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'full_name',
    NEW.raw_user_meta_data->>'avatar_url'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ────────────────────────────────────────────────────────────────
ALTER TABLE profiles  ENABLE ROW LEVEL SECURITY;
ALTER TABLE councils  ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles: own row"         ON profiles;
DROP POLICY IF EXISTS "councils: own rows"         ON councils;
DROP POLICY IF EXISTS "templates: own rows"        ON templates;
DROP POLICY IF EXISTS "templates: public readable" ON templates;

CREATE POLICY "profiles: own row" ON profiles
  FOR ALL USING (auth.uid() = id);

CREATE POLICY "councils: own rows" ON councils
  FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "templates: own rows" ON templates
  FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "templates: public readable" ON templates
  FOR SELECT USING (is_public = TRUE);

-- ────────────────────────────────────────────────────────────────
-- ATOMIC DECREMENT FUNCTION
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION decrement_credit(p_user_id UUID)
RETURNS TABLE(credits_remaining INTEGER, success BOOLEAN)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_new_credits INTEGER;
BEGIN
  UPDATE profiles
  SET credits_remaining = profiles.credits_remaining - 1
  WHERE id = p_user_id
    AND profiles.credits_remaining > 0
  RETURNING profiles.credits_remaining INTO v_new_credits;

  IF FOUND THEN
    RETURN QUERY SELECT v_new_credits, TRUE;
  ELSE
    RETURN QUERY
      SELECT p.credits_remaining, FALSE
      FROM profiles p
      WHERE p.id = p_user_id;
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION decrement_credit(UUID) TO authenticated;
